name: React FastAPI CI/CD

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #################################################
      # BUILD FRONTEND IMAGE
      #################################################

      - name: Build Frontend Image
        run: |
          docker build \
            -t k1n9m0n73/react-frontend:latest \
            ./frontend

      - name: Push Frontend Image
        run: |
          docker push k1n9m0n73/react-frontend:latest

      #################################################
      # BUILD BACKEND IMAGE
      #################################################

      - name: Build Backend Image
        run: |
          docker build \
            -t k1n9m0n73/fastapi-backend:latest \
            ./backend

      - name: Push Backend Image
        run: |
          docker push k1n9m0n73/fastapi-backend:latest

      #################################################
      # DEPLOY TO VM
      #################################################

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 44

          script: |

            set -e

            cd ~/projects/react-fastapi-devops

            echo "===== PULL LATEST IMAGES ====="

            docker compose pull

            echo "===== RESTART SERVICES ====="

            docker compose up -d

            echo "===== WAITING FOR SERVICES ====="

            sleep 15

            echo "===== HEALTH CHECK ====="

            curl -f http://localhost/api/health

            echo "===== DEPLOYMENT SUCCESS ====="

            docker ps

